apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
   ingress_type: ingress
   ingress_tls_secret: awx-secret-tls
   hostname: awx.labtest.com.py
   projects_persistence: true
   projects_storage_class: nfs-client
   postgres_storage_class: nfs-client
   projects_storage_access_mode: ReadWriteOnce
   web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/awx/public
   extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: public-static-data-pvc
