---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - server.crt
      - server.key
   - name: awx-admin-password
     type: Opaque
     literals:
       - password=Admin123!
resources:
      - namespace.yml
      - pvc.yml
      - awx.yml  
